---
- name: Ensure apt is updated and packages are managed
  hosts: all
  become: yes

  tasks:
    - name: Update the apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Ensure required packages are installed
      apt:
        name:
          - git
          - htop
          - neovim
        state: present 
    - name: Add Google Cloud SDK apt repository keyring
      shell: |
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
      args:
        creates: /usr/share/keyrings/cloud.google.gpg

    - name: Add Google Cloud SDK apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
        state: present

    - name: Update apt cache after adding Google Cloud SDK repository
      apt:
        update_cache: yes

    - name: Install Google Cloud SDK
      apt:
        name: google-cloud-sdk
        state: present 

    - name: Ensure AWS CLI dependencies are installed
      apt:
        name:
          - unzip
          - curl
        state: present

    - name: Check if AWS CLI is installed
      command: aws --version
      register: aws_cli_check
      ignore_errors: yes

    - name: Download AWS CLI installer if not installed
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
      when: aws_cli_check.rc != 0

    - name: Unzip AWS CLI installer if not installed
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes
      when: aws_cli_check.rc != 0

    - name: Install AWS CLI if not installed
      command: /tmp/aws/install
      when: aws_cli_check.rc != 0

    - name: Verify AWS CLI installation
      command: aws --version
      register: aws_cli_version
      ignore_errors: yes
